### ISSUE TITLE
ch.qos.logback:logback-core is a logback-core module

### ISSUE THREAD

**Issue by bhaskarvilles** [tiki/kgraph#10]
Insufficient Hostname Verification in ch.qos.logback:logback-core

ch.qos.logback:logback-core is a logback-core module.

Affected versions of this package are vulnerable to Insufficient Hostname Verification. X.509 are not properly validated. By spoofing the TLS/SSL server via a certificate that appears valid, an attacker with the ability to intercept network traffic (e.g. MitM, DNS cache poisoning) can disclose and optionally manipulate transmitted data.

Upgrade ch.qos.logback:logback-core to version 1.2.7 or higher.

**Comment by mike-audi** [comment]
confirmed. will bump version with next release. thank you

**Comment by mike-audi** [comment]
<img width="892" alt="Screen Shot 2022-03-13 at 11 50 00 PM" src="https://user-images.githubusercontent.com/3769672/158106973-c59bc355-3e93-4d3c-8fc8-38cd6fb5241d.png">
<img width="893" alt="Screen Shot 2022-03-13 at 11 50 36 PM" src="https://user-images.githubusercontent.com/3769672/158106974-440f230b-55cd-4db4-a5f4-8acd58e92f67.png">
