### ISSUE TITLE
Determine unique occurrence ID pattern for emails

### ISSUE THREAD

**Issue by sfaria27** [tiki/kgraph#12]
Determine identification pattern for unique occurrences of emails when adding vertices to kgraph

Acceptance criteria:
1. when multiple users get email, it should show up as single vertex
2. when singular user gets email, it should show up as as a single vertex
3. when multiple users get singular emails, it should show up as multiple vertices

**Comment by mike-audi** [comment]
~Use the following parameters for unique occurrence detection:~

~From (sender email)~
~Received Date (use 72 hour window)~
~Sanitized Subject (redact PII)~

~Note: allow the app to submit a flag to force uniqueness for things like emails with an order#~

**Comment by mike-audi** [comment]
~We can generate a new unique occurrence id (OID) for each email by hashing the message id with the receiver email address~

**Comment by mike-audi** [comment]
We can compute the occurrence id (OID) for an email by:

`sha256(sender_email, sanitized_subject, date_range_number)`

where date_range_number is time since epoch divided by block size, rounded down. 

for example
```
current time (s): 1645827065
block size (s): 259200 [3 days]

date range number: 1645827065/259200 = 6349
```
