### ISSUE TITLE
Determine how to fix data ingestion

### ISSUE THREAD

**Issue by sfaria27** [tiki/kgraph#14]
Currently we can't add data to the knowledge graph (without it "exploding")

Acceptance criteria:
1. Should be able to ingest 10mm points per day

**Comment by mike-audi** [comment]
Arango supports multiple inserts per transaction as long as they're within the same collection. Our current structure has a single collection for all edges. 


To improve ingestion we create a staging table in the ingestion service of edges, segmented by updates, and inserts, then when we hit a threshold, for example 1000 rows or 30 minutes, we bulk commit. 

In addition to the staging table, we need to add bulk PUT & POST methods to the graph service.
