### ISSUE TITLE
Add support for running query needed to generate top subject lines insight

### ISSUE THREAD

**Issue by NickkTMD** [tiki/kgraph#35]
Currently kgraph supports operations like traversals,  shortestPath, and findByVertices. Many insights will need more complicated queries with more complex filters. 

for top subject lines, we will want something like:

**CORRECTED QUERY:**
```
FOR v, e, p IN 2..2 ANY @company GRAPH "kgraph"
    FILTER (FOR v2, e2 IN 1..1 ANY p.vertices[1] GRAPH "kgraph" FILTER v2._id == "action/email" RETURN 1) == [1] 
    RETURN (FOR v2, e2 IN 1..1 ANY p.vertices[1] GRAPH "kgraph" FILTER IS_SAME_COLLECTION("subject", v2) RETURN {"subject": v2.subject, "occurrences": 1/e2.weight})
```

Where `@company` is the _key value of the company we are looking at, and `@startingDate` and `@endingDate` define a date range (dates are strings like 06/27/2022). 

Acceptance Criteria:
1. kgraph repo can be used to run query which returns json data from which top subjects insight can be calculated.

**Comment by mike-audi** [comment]
api works but either the query or the kgraph itself isn't working.


![Image](https://user-images.githubusercontent.com/3769672/177251758-45316ca3-993a-45cb-81c1-fb7a15654967.png)

**Comment by mike-audi** [comment]
ingest service is the issue.

**Comment by NickkTMD** [comment]
corrected query:
```
FOR v, e, p IN 2..2 ANY @company GRAPH "kgraph"
    FILTER (FOR v2, e2 IN 1..1 ANY p.vertices[1] GRAPH "kgraph" FILTER v2._id == "action/email" RETURN 1) == [1] 
    RETURN (FOR v2, e2 IN 1..1 ANY p.vertices[1] GRAPH "kgraph" FILTER IS_SAME_COLLECTION("subject", v2) RETURN {"subject": v2.subject, "occurrences": 1/e2.weight})
```

assuming the email has _id "action/email". v2.subject should be changed depending on subject line property name.
